### ISSUE TITLE
inputs appear to act as if given twice

### ISSUE THREAD

**Issue by Lord-LightSpeed** [tertsdiepraam/hexview#1]
Tapping an arrow key will move the cursor by two, and changing alignment switches twice and attempting to toggle inspector briefly opens it then closes it.
This may be that an update piece of code is called twice by every input.

for examples:
pressing the right arrow key with the cursor at position 00 moves the cursor to 02 and pressing the down arrow key from that point moves the cursor to 22
with alignment set to NAT pressing Ctrl+A changes alignment to 2 after skipping alignment 1
pressing I opens the inspector then closes it before it can be read from

other interesting effects:
using ? to exit the help screen also causes the HEX search to open
using q to exit the help screen causes the entire program to close

**Comment by tertsdiepraam** [comment]
Hi! Thanks for reporting!

I just tried reproducing this, but it works fine on my machine:tm:. Could you give some more information about your setup? For example, what are your OS and terminal emulator?

**Comment by Lord-LightSpeed** [comment]
OS: Windows 11 Home
OS Version: 10.0.22631
Terminal: Windows Terminal Preview
Shell: nushell
Shell Version: 0.98.0
other potential interests: running on a laptop, however an external keyboard still has the same problem

this is all that I can think would probably be causing it.
the same problem occurs if using command prompt as the shell
and also still occurs if I use the normal windows terminal
